language: node_js
node_js:
  - '8.11.1'

branches:
  only:
    - master

before_script:
  - npm install -g @vue/cli

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: dist